### ISSUE TITLE
Class added by cell class generator not used 

### ISSUE THREAD

**Issue by cbwhitebu** [vaadin/components#115]
I have a cell class generator that adds a class to table cells but the styles defined for the class in my component are never used.

Style:
```
<dom-module is="cf-main">
    <style>
        .currency {
            text-align: right;
        }
    </style>
```
Class generator:
```
this.$.pledges.cellClassGenerator = function(cell) {
    if (cell.index == 1) {
        return 'currency';
     }
     return '';
};
```

Attached image from Chrome debugger that shows that the td element has the 'currency' class but does not have the text-align property set. This might just be a Polymer limitation with scoped styling. Any suggestion for how to set the text-align property on a cell would be appreciated.

![td-class-issue](https://cloud.githubusercontent.com/assets/864976/9563969/130d16c6-4e4b-11e5-951a-84de38b7aac1.png)

**Comment by jounik** [comment]
I believe this is because Polymer does the style-scoping magic for your selectors that you write in your don-module.

Check from the `<head>` of your page what selectors are generated inside the `<style scope="cf-main">`. I believe the `.currency` class will be converted to `.currency.cf-main`, which no longer matches the class in the actual `v-grid` element.

You should be able to prevent the Polymer style scoping rules by using the `::content` pseudo element:

```css
:host ::content .currency {
  text-align: right;
}
```

**Comment by jounik** [comment]
Closing this as it is not related to the vaadin-grid element itself. Please re-open if you feel otherwise.
