### ISSUE TITLE
Failed to execute write on Document

### ISSUE THREAD

**Issue by antonmoiseev** [vaadin/components#16]
Hi I'm getting this warning while attempting to add `<v-grid>` to my project:
```
Failed to execute 'write' on 'Document': It isn't possible to write into a document
from an asynchronously-loaded external script unless it is explicitly opened.

VaadinGridImport.nocache.js:3
```
The gird's header is rendered but the content is missing. With inline data everything works fine.

**Comment by jounik** [comment]
I think the warning can be safely ignored, although it is annoying. We can see if we can get rid of that completely.

The second issue sounds more like it’s an actual problem. Can you share the code which causes it?

**Comment by WilliamQAFE** [comment]
I'm having the same issues when trying to use the vaadin-grid component in my Polymer application.
The header is rendered but the contents remain empty.

Code relevant to the issue:
inside my template I have a v-grid element:
```html
...
<v-grid>
  <table>
    <col name="date" header-text="Date">
    <col name="time" header-text="Time">
    <col name="action" header-text="Action">
    <col name="creditsLeft" header-text="Available Credits">
    <col name="fileName" header-text="Description">
  </table>
</v-grid>
...
```
(I have also tried different approaches such as using index. as a prefix for the names)

iron-ajax element which is fired asynchronously from another location (so not on ready).
```html
...
<iron-ajax handle-as="json"
       method="GET"
       on-response="handleCreditEntriesResponse"
       response="{{creditsEntriesResponse}}"
       headers="{{headers}}"
       loading="{{loading}}"
       on-error="onCreditsEntriesError"
       content-type="application/json"
       id="conversionHistoryAjax">
</iron-ajax>
...
```

Inside my Polymer({}) definitions:
```javascript
...
handleCreditEntriesResponse: function(creditsEntriesResponse) {
  ...
  var grid = document.querySelector('v-grid');
  grid.source = creditsEntriesResponse.detail.response;
  ...
}
...
```
Also, in your tutorials you use grid.data.source but this causes a 'data' undefined error.

**Comment by jounik** [comment]
Hi @WilliamQAFE,

The document.write is irrelevant for your issue, it’s just a warning, and we know about it and it doesn’t affect the functionality of the component.

The reason for `grid.data` being undefined is most likely because you try to access it before the custom element is upgraded and the component API is available. `grid.source` will definitely not do anything.

What version of vaadin-components are you using? Be sure to use the latest 0.3.0-beta1, since we fixed a major asynchronous loading issue related to the element upgrading on polyfilled browsers in that version. The current version you get from bower without specifying a version number is 0.2.1.

**Comment by WilliamQAFE** [comment]
We are using the latest 0.3.0-beta1 version indeed.

I got the data.source thing to work if I set it in the ready function. So all is well.
Thanks for the feedback!
