### ISSUE TITLE
<v-grid> Column max-width does not cut content if content is wider than the max-width value

### ISSUE THREAD

**Issue by Saulis** [vaadin/components#46]
For example, 

given we have a `<col max-width="100">` in use, and the styles `padding-left: 24px` and `padding-right: 28px` applied to the column in question using `td`, the actual Column width calculated by the Grid is something else than `100px`.

There's a fat chance that the Grid assumes that the padding is `24px` on both sides and bases it's calculations on that.

**Comment by tepi** [comment]
Can't reproduce with the current version. When testing, please note Grid currently works so that the column max width does not cut content. It merely sets a maximum limit to which the column can grow when it's in expanding mode. So if you have content with a width of 150px and set max-width to 100, it will have practically no effect.

I found the paddings irrelevant to the issue since they are not ever measured by the grid. The cell is border-box and grid only sets width to it.

If the behavior is wrong, maybe we should do a ticket to dev.vaadin.com (and provide a patch).

**Comment by tepi** [comment]
Ticket for core framework: https://dev.vaadin.com/ticket/18617

**Comment by tepi** [comment]
Will create a patch for Vaadin Framework and apply it to our forked grid...
